[tox]
env_list = unit-test, mypy, ruff-check

[testenv]
runner = uv-venv-runner
package = uv-editable
base_python = python3.12
extras = dev

[testenv:unit-test]
description = Run unit tests
commands = python -m pytest {posargs}

[testenv:mypy]
description = Run static type checks
commands = mypy google_find_my_ha publish_mqtt.py chrome_driver.py {posargs}

[testenv:ruff-check]
description = Run Ruff checks
commands = ruff check . {posargs}

[testenv:ruff-fix]
description = Fix Ruff check violations
commands = ruff check --fix . {posargs}
