# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: LocationReportsUpload.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import google_find_my_ha.ProtoDecoders.Common_pb2 as Common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1bLocationReportsUpload.proto\x1a\x0c\x43ommon.proto\"|\n\x15LocationReportsUpload\x12\x18\n\x07reports\x18\x01 \x03(\x0b\x32\x07.Report\x12\'\n\x0e\x63lientMetadata\x18\x02 \x01(\x0b\x32\x0f.ClientMetadata\x12\x0f\n\x07random1\x18\x03 \x01(\x04\x12\x0f\n\x07random2\x18\x04 \x01(\x04\"g\n\x06Report\x12%\n\radvertisement\x18\x01 \x01(\x0b\x32\x0e.Advertisement\x12\x13\n\x04time\x18\x04 \x01(\x0b\x32\x05.Time\x12!\n\x08location\x18\x06 \x01(\x0b\x32\x0f.LocationReport\"U\n\rAdvertisement\x12\x1f\n\nidentifier\x18\x05 \x01(\x0b\x32\x0b.Identifier\x12#\n\x1bunwantedTrackingModeEnabled\x18\x06 \x01(\r\";\n\nIdentifier\x12\x14\n\x0ctruncatedEid\x18\x06 \x01(\x0c\x12\x17\n\x0f\x63\x61nonicDeviceId\x18\x07 \x01(\x0c\"<\n\x0e\x43lientMetadata\x12*\n\x07version\x18\x02 \x01(\x0b\x32\x19.ClientVersionInformation\"7\n\x18\x43lientVersionInformation\x12\x1b\n\x13playServicesVersion\x18\x01 \x01(\tb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'LocationReportsUpload_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _LOCATIONREPORTSUPLOAD._serialized_start=45
  _LOCATIONREPORTSUPLOAD._serialized_end=169
  _REPORT._serialized_start=171
  _REPORT._serialized_end=274
  _ADVERTISEMENT._serialized_start=276
  _ADVERTISEMENT._serialized_end=361
  _IDENTIFIER._serialized_start=363
  _IDENTIFIER._serialized_end=422
  _CLIENTMETADATA._serialized_start=424
  _CLIENTMETADATA._serialized_end=484
  _CLIENTVERSIONINFORMATION._serialized_start=486
  _CLIENTVERSIONINFORMATION._serialized_end=541
# @@protoc_insertion_point(module_scope)
